# Dicoogle Indexer Configuration Properties
dicoogle.query.providers=lucene
dicoogle.index.providers=lucene
dicoogle.storage.providers=file

# Storage Directory inside container
dicoogle.storage.file.path=/data/storage
dicoogle.index.lucene.path=/data/index

# Network Ports
dicoogle.web.port=8081
dicoogle.dicom.port=104
